<fieldset>
    <legend>Report beneficiari</legend>
    <br /><br />
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Tipo report</label>
        <div class="col-sm-4">
            <select id="ddlTipoReport" class="form-select">
                <option value="">-- seleziona --</option>
                <option value="SG">Per settore, a parità di anno</option>
                <option value="TG">Per tipologia, a parità di anno</option>
                <option value="SS">Per anno, a parità di settore</option>
                <option value="TS">Per anno, a parità di tipologia</option>
            </select>                    
        </div>
    </div>
    <div id="divReportAnno" class="mb-3 row" style="display: none;">
        <label class="col-sm-2 col-form-label">Anno di riferimento</label>
        <div class="col-sm-2">
            <select id="ddlReportAnno" class="form-select"></select>                    
        </div>
    </div>
    <div id="divReportSettore" class="mb-3 row" style="display: none;">
        <label class="col-sm-2 col-form-label">Settore</label>
        <div class="col-sm-6">
            <select id="ddlReportSettore" class="form-select">
                <option value="">-- seleziona --</option>
            </select>                    
        </div>
    </div>
    <div id="divReportTipologia" class="mb-3 row" style="display: none;">
        <label class="col-sm-2 col-form-label">Tipologia</label>
        <div class="col-sm-4">
            <select id="ddlReportTipologia" class="form-select">
                <option value="">-- seleziona --</option>            
            </select>                    
        </div>
    </div>
    <div id="divEstraiReport" style="display: none;">
        <br />
        <div class="mb-3 row">
            <div class="col-sm-12">
                <button class="btn btn-primary btnEstraiReport">Estrai report</button>
            </div>
        </div>
    </div>
    <div id="divChartBeneficiari" style="display: none; height: 600px; padding-top: 20px;">
        <canvas id="chartBeneficiari"></canvas>
    </div>
    <div id="divNessunReport" style="display: none; font-weight: bold;">
        <br />
        Nessun dato disponibile per la generazione del report.
    </div>
</fieldset>

<script type="text/javascript">
    $(document).ready(function () {
        var self = this;
        
        self.get_tipologie = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_tipologie.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlReportTipologia").append("<option>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        self.get_settori = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_settori.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlReportSettore").append("<option>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        self.get_anni_riferimento = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_anni_riferimento.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlReportAnno").append("<option value='" + item + "'>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        $("#ddlTipoReport").change(function () {
            switch ($(this).val()) {
                case "SG": 
                case "TG": {
                    $("#divReportSettore").hide();
                    $("#divReportTipologia").hide();
                    $("#ddlReportTipologia").val("");
                    $("#ddlReportSettore").val("");
                    $("#divReportAnno").show();
                    $("#divEstraiReport").show();
                    break;
                }
                case "SS": {
                    $("#divReportSettore").show();
                    $("#divReportTipologia").hide();
                    $("#ddlReportTipologia").val("");
                    $("#divReportAnno").hide();
                    $("#divEstraiReport").hide();
                    break;
                }
                case "TS": {
                    $("#divReportTipologia").show();
                    $("#divReportSettore").hide();
                    $("#ddlReportSettore").val("");
                    $("#divReportAnno").hide();
                    $("#divEstraiReport").hide();
                    break;
                }
                default: {
                    $("#divReportSettore").hide();
                    $("#divReportTipologia").hide();
                    $("#ddlReportTipologia").val("");
                    $("#ddlReportSettore").val("");
                    $("#divReportAnno").hide();
                    $("#divEstraiReport").hide();
                    break;
                }
            }
        });
        
        $("#ddlReportSettore, #ddlReportTipologia").change(function () {
            if ($(this).val() != "") {
                $("#divEstraiReport").show();
            }
            else {
                $("#divEstraiReport").hide();
            }
        });
        
        $(".btnEstraiReport").click(function (e) {
            e.preventDefault();
            var url = "";
            var dto = null;
            switch ($("#ddlTipoReport").val()) {
                case "SG": {
                    url = "<?php echo API_URL; ?>beneficiario/report_settore.php";
                    dto = { anno: $("#ddlReportAnno").val() };
                    break;
                }
                case "TG": {
                    url = "<?php echo API_URL; ?>beneficiario/report_tipologia.php";
                    dto = { anno: $("#ddlReportAnno").val() };
                    break;
                }
                case "SS": {
                    url = "<?php echo API_URL; ?>beneficiario/report_settore_anno.php";
                    dto = { settore: $("#ddlReportSettore").val() };
                    break;
                }
                case "TS": {
                    url = "<?php echo API_URL; ?>beneficiario/report_tipologia_anno.php";
                    dto = { tipologia: $("#ddlReportTipologia").val() };
                    break;
                }
                default: {
                    return;
                }
            }
            $.ajax({
                url: url,
                type: "POST",
                data: dto,
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $("#chartBeneficiari").remove();
                    if (response.length > 0) {
                        var chartLabels = [];
                        var chartData = [];
                        $("#divChartBeneficiari").append("<canvas id=\"chartBeneficiari\"></canvas>");
                        var chart = null;
                        switch ($("#ddlTipoReport").val()) {
                            case "SG": {
                                $.each(response, function (i, item) {
                                    chartLabels.push(formatLabel(item.settore, 30));
                                    chartData.push(item.importo_annuale);
                                });
                                chart = new Chart($("#chartBeneficiari"), {
                                    type: "bar",
                                    data: {
                                        labels: chartLabels,
                                        datasets: [{
                                            label: "IMPORTO ANNUALE €",
                                            data: chartData,
                                            backgroundColor: ["rgba(0, 116, 217, 0.2)", "rgba(255, 65, 54, 0.2)", "rgba(46, 204, 64, 0.2)", "rgba(255, 133, 27, 0.2)", "rgba(127, 219, 255, 0.2)", "rgba(177, 13, 201, 0.2)", "rgba(255, 220, 0, 0.2)", "rgba(0, 31, 63, 0.2)", "rgba(57, 204, 204, 0.2)", "rgba(1, 255, 112, 0.2)", "rgba(133, 20, 75, 0.2)", "rgba(240, 18, 190, 0.2)", "rgba(61, 153, 112, 0.2)", "rgba(17, 17, 17, 0.2)", "rgba(170, 170, 170, 0.2)"],
                                            borderColor: ["rgba(0, 116, 217, 1)", "rgba(255, 65, 54, 1)", "rgba(46, 204, 64, 1)", "rgba(255, 133, 27, 1)", "rgba(127, 219, 255, 1)", "rgba(177, 13, 201, 1)", "rgba(255, 220, 0, 1)", "rgba(0, 31, 63, 1)", "rgba(57, 204, 204, 1)", "rgba(1, 255, 112, 1)", "rgba(133, 20, 75, 1)", "rgba(240, 18, 190, 1)", "rgba(61, 153, 112, 1)", "rgba(17, 17, 17, 1)", "rgba(170, 170, 170, 1)"],
                                            borderWidth: 1
                                        }]
                                    },
                                    options: {
                                        responsive: true,
                                        maintainAspectRatio: false,
                                        plugins: {
                                            title: {
                                                display: true,
                                                text: "REPORT SETTORI ANNO " + $("#ddlReportAnno option:selected").text(),
                                                padding: {
                                                    top: 10,
                                                    bottom: 30
                                                },
                                                font: {
                                                    size: 18
                                                }
                                            }
                                        },
                                        scales: {
                                            y: {
                                                beginAtZero: true
                                            }
                                        }
                                    }
                                });
                                break;
                            }
                            case "TG": {
                                $.each(response, function (i, item) {
                                    chartLabels.push(item.tipologia);
                                    chartData.push(item.importo_annuale);
                                });
                                chart = new Chart($("#chartBeneficiari"), {
                                    type: "bar",
                                    data: {
                                        labels: chartLabels,
                                        datasets: [{
                                            label: "IMPORTO ANNUALE €",
                                            data: chartData,
                                            backgroundColor: ["rgba(0, 116, 217, 0.2)", "rgba(255, 65, 54, 0.2)", "rgba(46, 204, 64, 0.2)", "rgba(255, 133, 27, 0.2)", "rgba(127, 219, 255, 0.2)", "rgba(177, 13, 201, 0.2)", "rgba(255, 220, 0, 0.2)", "rgba(0, 31, 63, 0.2)", "rgba(57, 204, 204, 0.2)", "rgba(1, 255, 112, 0.2)", "rgba(133, 20, 75, 0.2)", "rgba(240, 18, 190, 0.2)", "rgba(61, 153, 112, 0.2)", "rgba(17, 17, 17, 0.2)", "rgba(170, 170, 170, 0.2)"],
                                            borderColor: ["rgba(0, 116, 217, 1)", "rgba(255, 65, 54, 1)", "rgba(46, 204, 64, 1)", "rgba(255, 133, 27, 1)", "rgba(127, 219, 255, 1)", "rgba(177, 13, 201, 1)", "rgba(255, 220, 0, 1)", "rgba(0, 31, 63, 1)", "rgba(57, 204, 204, 1)", "rgba(1, 255, 112, 1)", "rgba(133, 20, 75, 1)", "rgba(240, 18, 190, 1)", "rgba(61, 153, 112, 1)", "rgba(17, 17, 17, 1)", "rgba(170, 170, 170, 1)"],
                                            borderWidth: 1
                                        }]
                                    },
                                    options: {
                                        responsive: true,
                                        maintainAspectRatio: false,
                                        plugins: {
                                            title: {
                                                display: true,
                                                text: "REPORT TIPOLOGIE ANNO " + $("#ddlReportAnno option:selected").text(),
                                                padding: {
                                                    top: 10,
                                                    bottom: 30
                                                },
                                                font: {
                                                    size: 18
                                                }
                                            }
                                        },
                                        scales: {
                                            y: {
                                                beginAtZero: true
                                            }
                                        }
                                    }
                                });
                                break;
                            }
                            case "SS":
                            case "TS": {
                                $.each(response, function (i, item) {
                                    chartLabels.push(item.anno);
                                    chartData.push(item.importo_annuale);
                                });
                                chart = new Chart($("#chartBeneficiari"), {
                                    type: "bar",
                                    data: {
                                        labels: chartLabels,
                                        datasets: [{
                                            label: "IMPORTO ANNUALE €",
                                            data: chartData,
                                            backgroundColor: ["rgba(0, 116, 217, 0.2)", "rgba(255, 65, 54, 0.2)", "rgba(46, 204, 64, 0.2)", "rgba(255, 133, 27, 0.2)", "rgba(127, 219, 255, 0.2)", "rgba(177, 13, 201, 0.2)", "rgba(255, 220, 0, 0.2)", "rgba(0, 31, 63, 0.2)", "rgba(57, 204, 204, 0.2)", "rgba(1, 255, 112, 0.2)", "rgba(133, 20, 75, 0.2)", "rgba(240, 18, 190, 0.2)", "rgba(61, 153, 112, 0.2)", "rgba(17, 17, 17, 0.2)", "rgba(170, 170, 170, 0.2)"],
                                            borderColor: ["rgba(0, 116, 217, 1)", "rgba(255, 65, 54, 1)", "rgba(46, 204, 64, 1)", "rgba(255, 133, 27, 1)", "rgba(127, 219, 255, 1)", "rgba(177, 13, 201, 1)", "rgba(255, 220, 0, 1)", "rgba(0, 31, 63, 1)", "rgba(57, 204, 204, 1)", "rgba(1, 255, 112, 1)", "rgba(133, 20, 75, 1)", "rgba(240, 18, 190, 1)", "rgba(61, 153, 112, 1)", "rgba(17, 17, 17, 1)", "rgba(170, 170, 170, 1)"],
                                            borderWidth: 1
                                        }]
                                    },
                                    options: {
                                        responsive: true,
                                        maintainAspectRatio: false,
                                        plugins: {
                                            title: {
                                                display: true,
                                                text: $("#ddlTipoReport").val() == "SS" ? $("#ddlReportSettore option:selected").text() : $("#ddlReportTipologia option:selected").text(),
                                                padding: {
                                                    top: 10,
                                                    bottom: 30
                                                },
                                                font: {
                                                    size: 18
                                                }
                                            }
                                        },
                                        scales: {
                                            y: {
                                                beginAtZero: true
                                            }
                                        }
                                    }
                                });
                                break;
                            }
                            default: {
                                return;
                            }
                        }
                        $("#divNessunReport").hide();
                        $("#divChartBeneficiari").show();
                    }
                    else {
                        $("#divNessunReport").show();
                        $("#divChartBeneficiari").hide();
                    }
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        });
        
        self.get_tipologie();
        self.get_settori();
        self.get_anni_riferimento();
    });
    
    function formatLabel(str, maxWidth) {
        var sections = [];
        var words = str.split(" ");
        var temp = "";
        words.forEach(function (item, index) {
            if (temp.length > 0) {
                var concat = temp + " " + item;
                if (concat.length > maxWidth) {
                    sections.push(temp);
                    temp = "";
                }
                else {
                    if (index == words.length - 1) {
                        sections.push(concat);
                        return;
                    }
                    temp = concat;
                    return;
                }
            }
            if (index == words.length - 1) {
                sections.push(item);
                return;
            }
            if (item.length < maxWidth) {
                temp = item;
            }
            else {
                sections.push(item);
            }
        });
        return sections;
    };
</script>