<fieldset>
    <legend>Archivio beneficiari</legend>
    <br /><br />
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Anno di riferimento</label>
        <div class="col-sm-2">
            <select id="ddlAnno" class="form-select"></select>                    
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Beneficiario</label>
        <div class="col-sm-8">
            <input id="txtBeneficiario" type="text" class="form-control">
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Settore</label>
        <div class="col-sm-6">
            <select id="ddlSettore" class="form-select">
                <option value="">-- seleziona --</option>
            </select>                    
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Tipologia</label>
        <div class="col-sm-4">
            <select id="ddlTipologia" class="form-select">
                <option value="">-- seleziona --</option>            
            </select>                    
        </div>
    </div>
    <br />
    <div class="mb-3 row">
        <div class="col-sm-12">
            <button class="btn btn-primary btnAvviaRicercaBeneficiari">Avvia ricerca</button>
        </div>
    </div>
    <br />
    <div id="divRisultati" class="mb-3" style="display: none;">     
        <p style="font-size: 20px; text-align: right;">TOTALE IMPORTO: <span id="totImporto" style="font-weight: bold;"></span></p>
        <br />
        <div id="paginator"></div>
        <br /><br />  
        <table id="tblRisultati" class="table table-striped table-hover">
            <thead class="table-dark">
                <tr style="text-align: center; vertical-align: middle;">
                    <th>TIPOLOGIA</th>
                    <th>BENEFICIARIO</th>
                    <th>IMPORTO</th>
                    <th>NORMA O TITOLO ATTRIBUZIONE</th>
                    <th>SETTORE</th>
                    <th>ATTO</th>
                    <th>PROGETTO/FINALIT&Agrave;</th>
                </tr>
            </thead>
            <tbody style="text-align: center; vertical-align: middle;"></tbody> 
        </table>
    </div>
    <p id="pNessunRisultato" style="display: none; font-weight: bold;">Nessun risultato disponibile.</p>
</fieldset>

<script type="text/javascript">
    $(document).ready(function () {
        var self = this;
        
        self.get_tipologie = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_tipologie.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlTipologia").append("<option>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        self.get_settori = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_settori.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlSettore").append("<option>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        self.get_anni_riferimento = function () {
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/get_anni_riferimento.php",
                type: "GET",
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $.each(response, function (i, item) {
                        $("#ddlAnno").append("<option value='" + item + "'>" + item + "</option>");
                    });
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        };
        
        $(".btnAvviaRicercaBeneficiari").click(function (e) {
            e.preventDefault();
            var dto = {
                anno: $("#ddlAnno").val(),
                tipologia: $("#ddlTipologia").val(),
                beneficiario: $("#txtBeneficiario").val(),
                settore: $("#ddlSettore").val()
            };
            $.ajax({
                url: "<?php echo API_URL; ?>beneficiario/ricerca.php",
                type: "POST",
                data: dto,
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    var formatter = new Intl.NumberFormat("it-IT", {
                        style: "currency",
                        currency: "EUR"
                    });
                    $("#tblRisultati tbody").empty();
                    if (response.risultati.length > 0) {
                        // paginazione
                        $("#paginator").pagination({
                            dataSource: response.risultati,
                            pageNumber: 1,
                            pageSize: 10,
                            pageRange: 2,
                            className: "paginationjs paginationjs-big",
                            callback: function (data, pagination) {
                                $("#tblRisultati tbody").empty();
                                var trHTML = "";
                                $.each(data, function (i, item) {
                                    trHTML += "<tr><td>" + item.tipologia + 
                                              "</td><td>" + item.beneficiario +
                                              "</td><td>" + formatter.format(item.importo) +
                                              "</td><td>" + item.norma_titolo_attr +
                                              "</td><td>" + item.settore +
                                              "</td><td>" + item.atto +
                                              "</td><td>" + item.progetto_finalita +
                                              "</td></tr>";
                                });
                                $("#tblRisultati tbody").append(trHTML);
                            }
                        });                 
                        $("#totImporto").text(formatter.format(response.tot_importo));
                        $("#pNessunRisultato").hide();
                        $("#divRisultati").show();
                    }
                    else {
                        $("#totImporto").text(formatter.format(0));
                        $("#pNessunRisultato").show();
                        $("#divRisultati").hide();
                    }
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        });
        
        self.get_tipologie();
        self.get_settori();
        self.get_anni_riferimento();
    });
</script>