<fieldset>
    <legend>Riepilogo occupazioni/rotazioni</legend>
    <br /><br />
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Via</label>
        <div class="col-sm-8">
            <input id="txtVia" type="text" class="form-control">
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Data di riferimento iniziale</label>
        <div class="col-sm-3">
            <input id="txtDataIni" type="text" class="form-control date">
        </div>
    </div>
    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Data di riferimento finale</label>
        <div class="col-sm-3">
            <input id="txtDataFin" type="text" class="form-control date">
        </div>
    </div>
    <br />
    <div class="mb-3 row">
        <div class="col-sm-12">
            <button class="btn btn-primary btnRiepilogoOccupazioni">Riepilogo occupazioni</button>&nbsp;&nbsp;
            <button class="btn btn-primary btnRiepilogoRotazioni">Riepilogo rotazioni</button>
        </div>
    </div>
    <br />
    <div id="divRiepilogoOccupazioni" class="mb-3" style="display: none;">
        <table id="tblRiepilogoOccupazioni" class="table table-striped table-hover">
            <thead class="table-dark">
                <tr style="text-align: center; vertical-align: middle;">
                    <th>VIA</th>
                    <th>NUM. STALLI COINVOLTI</th>
                    <th>TOT. DURATA OCCUPAZIONI (MINUTI)</th>
                    <th>RAPPORTO</th>
                </tr>
            </thead>
            <tbody style="text-align: center; vertical-align: middle;"></tbody> 
        </table>
    </div>
    <div id="divRiepilogoRotazioni" class="mb-3" style="display: none;">
        <table id="tblRiepilogoRotazioni" class="table table-striped table-hover">
            <thead class="table-dark">
                <tr style="text-align: center; vertical-align: middle;">
                    <th>VIA</th>
                    <th>NUM. STALLI COINVOLTI</th>
                    <th>NUM. ROTAZIONI</th>
                    <th>RAPPORTO</th>
                </tr>
            </thead>
            <tbody style="text-align: center; vertical-align: middle;"></tbody> 
        </table>
    </div>
    <p id="pNessunRisultato" style="display: none; font-weight: bold;">Nessun risultato disponibile.</p>
</fieldset>

<script type="text/javascript">
    $(document).ready(function () {
        $(".date").datepicker();
        
        $(".btnRiepilogoOccupazioni").click(function (e) {
            e.preventDefault();
            var dto = {
                data_ini: $("#txtDataIni").val(),
                data_fin: $("#txtDataFin").val(),
                via: $("#txtVia").val()
            };
            $.ajax({
                url: "<?php echo API_URL; ?>parcheggio/get_occupazioni.php",
                type: "POST",
                data: dto,
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $("#tblRiepilogoOccupazioni tbody").empty();
                    $("#divRiepilogoRotazioni").hide();
                    if (response.length > 0) {
                        var trHTML = "";
                        $.each(response, function (i, item) {
                            trHTML += "<tr><td>" + item.via + 
                                      "</td><td>" + item.num_parcheggi +
                                      "</td><td>" + item.somma_durata_sosta +
                                      "</td><td>" + item.rapporto +
                                      "</td></tr>";
                        });
                        $("#tblRiepilogoOccupazioni tbody").append(trHTML);
                        $("#pNessunRisultato").hide();
                        $("#divRiepilogoOccupazioni").show();
                    }
                    else {
                        $("#pNessunRisultato").show();
                        $("#divRiepilogoOccupazioni").hide();
                    }
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        });
        
        $(".btnRiepilogoRotazioni").click(function (e) {
            e.preventDefault();
            var dto = {
                data_ini: $("#txtDataIni").val(),
                data_fin: $("#txtDataFin").val(),
                via: $("#txtVia").val()
            };
            $.ajax({
                url: "<?php echo API_URL; ?>parcheggio/get_rotazioni.php",
                type: "POST",
                data: dto,
                dataType: "json",
                headers: {
                    "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                },
                success: function (response) {
                    $("#tblRiepilogoRotazioni tbody").empty();
                    $("#divRiepilogoOccupazioni").hide();
                    if (response.length > 0) {
                        var trHTML = "";
                        $.each(response, function (i, item) {
                            trHTML += "<tr><td>" + item.via + 
                                      "</td><td>" + item.num_parcheggi +
                                      "</td><td>" + item.num_rotazioni +
                                      "</td><td>" + item.rapporto +
                                      "</td></tr>";
                        });
                        $("#tblRiepilogoRotazioni tbody").append(trHTML);
                        $("#pNessunRisultato").hide();
                        $("#divRiepilogoRotazioni").show();
                    }
                    else {
                        $("#pNessunRisultato").show();
                        $("#divRiepilogoRotazioni").hide();
                    }
                },
                error: function (response) {
                    Swal.fire({
                        title: "Errore!",
                        text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                        icon: "error",
                        confirmButtonText: "Ok"
                    });
                }
            });
        });
    });
</script>