<?php

echo "<fieldset>" .
        "<legend>Importazione stalli</legend>" .
        "<br /><br />" .
        "<div class=\"mb-3 row\">" .
            "<div class=\"col-sm-12\">" .
                "<input type=\"file\" id=\"fupParcheggi\" name=\"fupParcheggi\">" .
            "</div>" .
        "</div>" .
        "<br />" .
        "<div class=\"mb-3 row\">" .
            "<div class=\"col-sm-12\">" .
                "<button class=\"btn btn-primary btnImporta\">Importa</button>" .
            "</div>" .
        "</div>" .
      "</fieldset>";
        
?>

<script type="text/javascript">
    $(document).ready(function () {
        $(".btnImporta").click(function (e) {
            e.preventDefault();
            var file = $("#fupParcheggi")[0].files[0];
            if (!file) {
                Swal.fire({
                    title: "Errore!",
                    text: "Caricare il file prima di procedere.",
                    icon: "error",
                    confirmButtonText: "Ok"
                });
            }
            else {
                Swal.fire({
                    title: "Operazione in corso",
                    text: "L'importazione potrebbe richiedere diversi minuti, attendere...",
                    icon: "info",
                    showConfirmButton: false,
                    allowOutsideClick: false
                });
                Swal.showLoading();
                var dto = new FormData();
                dto.append("token", "<?php echo !empty($_SESSION["user_token"]) ? $_SESSION["user_token"] : ""; ?>");
                dto.append("fupParcheggi", file);
                $.ajax({
                    url: "<?php echo API_URL; ?>parcheggio/importa.php",
                    type: "POST",
                    data: dto,
                    dataType: "json",
                    contentType: false,
                    processData: false,
                    headers: {
                        "Authorization": make_base_auth("<?php echo API_USER; ?>", "<?php echo API_PW; ?>")
                    },
                    success: function (response) {
                        Swal.fire({
                            title: "Operazione completata",
                            text: "Importazione avvenuta correttamente.",
                            icon: "success",
                            confirmButtonText: "Ok"
                        })
                        .then(function () {
                            $("#fupParcheggi").val("");
                        });
                    },
                    error: function (response) {
                        Swal.fire({
                            title: "Errore!",
                            text: response.responseJSON ? response.responseJSON.error_message : "Si è verificato un errore, contattare gli amministratori.",
                            icon: "error",
                            confirmButtonText: "Ok"
                        })
                        .then(function () {
                            $("#fupParcheggi").val("");
                        });
                    }
                });
            }
        });
    });
</script>