<?php

if (session_status() === PHP_SESSION_NONE) {
    session_start(); 
}

?>

<!DOCTYPE html>
<html lang="it">
    <head>
        <link rel="stylesheet" href="<?php echo "inc" . DS . "css" . DS . "bootstrap.min.css" ?>" />
        <link rel="stylesheet" href="<?php echo "inc" . DS . "css" . DS . "sweetalert2.min.css" ?>" />
        <link rel="stylesheet" href="<?php echo "inc" . DS . "css" . DS . "jquery-ui.min.css" ?>" />
        <link rel="stylesheet" href="<?php echo "inc" . DS . "css" . DS . "pagination.css" ?>" />
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "jquery-3.6.0.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "bootstrap.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "sweetalert2.all.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "jquery-ui.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "jquery.ui.datepicker-it.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "jquery.maskedinput-1.3.1.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "pagination.min.js" ?>"></script>
        <script type="text/javascript" src="<?php echo "inc" . DS . "js" . DS . "chart.min.js" ?>"></script>
        <title>InnoTV - Web App</title>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <!-- menu -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="?page=home"><img src="<?php echo "inc" . DS . "images" . DS . "logo-INNO-TV.png" ?>" alt="" class="w-100" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link <?php echo $page == "home" ? "active" : ""; ?>" aria-current="page" href="?page=home">HOME</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="beneficiariDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                BENEFICIARI
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="beneficiariDropdown">
                                <li><a class="dropdown-item" href="?page=beneficiari_archivio">Consulta archivio</a></li>
                                <li><a class="dropdown-item" href="?page=beneficiari_report">Estrai report</a></li>
                                <li style="display: <?php echo empty($_SESSION["user_id"]) ? "none;" : "block;"; ?>"><a class="dropdown-item" href="?page=beneficiari_importa">Importa archivio</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="parcheggiDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                STALLI
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="parcheggiDropdown">
                                <li><a class="dropdown-item" href="?page=parcheggi_archivio">Consulta archivio</a></li>
                                <li style="display: <?php echo empty($_SESSION["user_id"]) ? "none;" : "block;"; ?>"><a class="dropdown-item" href="?page=parcheggi_importa">Importa archivio</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="stranieriDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                CITTADINI STRANIERI
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="stranieriDropdown">
                                <li><a class="dropdown-item" href="?page=stranieri_report">Estrai report</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="poiDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                PUNTI DI INTERESSE
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="poiDropdown">
                                <li><a class="dropdown-item" href="?page=besta">Servizi pubblici accessibili</a></li>
                                <li><a class="dropdown-item" href="?page=defibrillatori">Defibrillatori</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?php echo $page == "frequenza_nomi" ? "active" : ""; ?>" aria-current="page" href="?page=frequenza_nomi">NOMI A TREVISO</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse w-25 order-3 dual-collapse2">
                    <ul class="navbar-nav ms-auto" style="padding-right: 50px;">
                        <li class="nav-item" style="display: <?php echo empty($_SESSION["user_id"]) ? "block;" : "none;"; ?>">
                            <a class="nav-link <?php echo $page == "login" ? "active" : ""; ?>" href="?page=login">AREA RISERVATA</a>
                        </li>
                        <li class="nav-item dropdown" style="display: <?php echo empty($_SESSION["user_id"]) ? "none;" : "block;"; ?>">
                            <a class="nav-link dropdown-toggle" href="#" id="nominativoDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <?php echo empty($_SESSION["user_id"]) ? "" : strtoupper($_SESSION["user_nominativo"]); ?>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="nominativoDropdown">
                                <li><a class="dropdown-item" href="?page=logout">Esci</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br /><br /><br />
        <!-- contenuto -->
        <div class="container main"><?php include $main_content; ?></div>
        <br /><br /><br />
        <!-- footer -->
        <footer class="bg-dark text-center text-white mt-auto">
            <br />
            <div class="container p-4">
                <section class="">
                    <div class="row">
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0"></div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0"></div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0">
                            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                                <a href="https://innotv.it/chi-siamo/#4" target="_blank">
                                    <img src="<?php echo "inc" . DS . "images" . DS . "logo-POR.png" ?>" />
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0">
                            <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                                <a href="#">
                                    <img src="<?php echo "inc" . DS . "images" . DS . "logo-Treviso.png" ?>" />
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0"></div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-md-0"></div>
                    </div>
                </section>
            </div>
            <br />
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                © <?php echo date("Y") ?> Copyright: #INNOTV Innovation Lab Treviso
            </div>
        </footer>
        
        <script type="text/javascript">
            $.datepicker.setDefaults($.extend({ dateFormat: "dd-mm-yy" }, $.datepicker.regional["it"]));

            $(document).on("focus", ".hasDatepicker", function () {
                $(this).prop("autocomplete", "off");
                $(this).mask("99/99/9999");
            });
            
            function make_base_auth(user, password) {
                var tok = user + ":" + password;
                var hash = btoa(tok);
                return "Basic " + hash;
            };
        </script>
    </body>
</html>